# Please insert new items alphabetically.
design-system-dev:
  members:
    - 36degrees
    - christopherthomasdesign
    - hannalaakso
    - joelanman
    - kellylee-gds
    - m-green
    - RosieClayton
    - StephenGill
    - timpaul

  include_repos:
    - accessible-autocomplete
    - design-system-support
    - design-system-team-credentials
    - design-system-team-docs
    - design-system-team-internal
    - design-system-team-labels
    - govuk-design-system
    - govuk-design-system-architecture
    - govuk-design-system-backlog
    - govuk-frontend
    - govuk-frontend-docs
    - govuk-prototype-kit
    - govuk-prototype-kit-docs
    - govuk_elements
    - govuk_elements_rails
    - govuk_frontend_toolkit
    - govuk_frontend_toolkit_gem
    - govuk_frontend_toolkit_npm
    - govuk_template
    - prototype-kit-training

  channel:
    "#design-system-dev"

  exclude_titles:
    - DO NOT MERGE
    - WIP

  compact: true

digitalmarketplace:
  members:
    - lfdebrux
    - gidsg
    - agalamatis
    - katstevens
    - phantas
    - domoscargin

  channel:
    "#dm-review"

  exclude_titles:
    - WIP

  include_repos:
    - "digitalmarketplace-admin-frontend"
    - "digitalmarketplace-agreements"
    - "digitalmarketplace-antivirus-api"
    - "digitalmarketplace-api"
    - "digitalmarketplace-apiclient"
    - "digitalmarketplace-aws"
    - "digitalmarketplace-bad-words"
    - "digitalmarketplace-brief-responses-frontend"
    - "digitalmarketplace-briefs-frontend"
    - "digitalmarketplace-buyer-frontend"
    - "digitalmarketplace-content-loader"
    - "digitalmarketplace-credentials"
    - "digitalmarketplace-design-patterns"
    - "digitalmarketplace-docker-base"
    - "digitalmarketplace-frameworks"
    - "digitalmarketplace-frontend-toolkit"
    - "digitalmarketplace-functional-tests"
    - "digitalmarketplace-govuk-frontend"
    - "digitalmarketplace-jenkins"
    - "digitalmarketplace-logdia"
    - "digitalmarketplace-manual"
    - "digitalmarketplace-performance-testing"
    - "digitalmarketplace-router"
    - "digitalmarketplace-runner"
    - "digitalmarketplace-scripts"
    - "digitalmarketplace-search-api"
    - "digitalmarketplace-supplier-frontend"
    - "digitalmarketplace-test-utils"
    - "digitalmarketplace-user-frontend"
    - "digitalmarketplace-utils"
    - "digitalmarketplace-visual-regression"
    - "govuk-frontend-jinja"

  compact: false

govuk-accounts:
  channel:
    "#govuk-accounts"

  quotes:
    - "We put users first. We strive to create services that bring real value to our users and that meet their needs and expectations."
    - "We believe users should feel safe and confident when they use our services."
    - "We design for everyone. We think about under-represented audiences from the start and check our biases throughout the design process."
    - "We’re comfortable challenging assumptions and asking difficult questions. We speak truth to power."
    - "We’re OK with change, failure, ambiguity, and adapting our approach."
    - "We work collaboratively. Our work does not happen in discipline silos and we value the contributions of every discipline equally."
    - "We treat each other with integrity, honesty and respect."
    - "We work in the open so users and government colleagues know what we’re doing and why."
    - "We know we can't do this alone. We need to work with teams across GDS and government to succeed."
    - "We invest time and effort in increasing our understanding of the problems we’re working on. This will help us make things better for users and move the conversation about personalisation in government forward."

govuk-accounts-tech:
  members:
    - andysellick
    - barrucadu
    - bevanloon
    - brucebolt
    - erino
    - huwd

  channel:
    "#govuk-accounts-tech"

  exclude_titles:
    - "[DO NOT MERGE]"
    - "[PROTOTYPE]"
    - WIP
    - "[WIP]"

govuk-brexit-content-team:
  members:
    - DilwoarH
    - hannako
    - sihugh

  channel:
    "#govuk-brexit-content-team"

  compact: true

  exclude_titles:
    - "[PROTOTYPE]"
    - WIP
    - "[WIP]"

govuk-corona-services:
  members:
    - alex-ju
    - gclssvglx
    - GDSNewt
    - JonathanHallam
    - leenagupte
    - reggieb
    - Rosa-Fox
    - steveholmes

  channel:
    "#govuk-corona-services-tech"

  exclude_titles:
    - "DO NOT MERGE"
    - "🚧"
    - "[WIP]"
    - "[Do Not Merge]"

  include_repos:
    - govuk-coronavirus-business-volunteer-form
    - govuk-coronavirus-find-support
    - govuk-coronavirus-vulnerable-people-form
    - govuk-developer-docs

govuk-data-labs:
  members:
    - chao-xian
    - ff-l
    - karlbaker02
    - mammykins
    - nacnudus
    - oscarwyatt
    - suganya-s
    - trvllngmn
    - VitalieMogoreanu

  channel:
    "#govuk-data-labs"

  exclude_titles:
    - "[DO NOT MERGE]"
    - "[PROTOTYPE]"
    - WIP
    - "[WIP]"

  quotes:
    - "Be Excellent To Each Other!"
    - ":smiling-batman:"
    - "Don't be working if you're ill!"
    - ":green_heart:"
    - "Remember to take into consideration that our colleagues may be having a hard time outside of work and support them at a team and individual level."
    - "Remember to avoid talking over each other during meetings, and are mindful of colleagues who wish to speak but have yet to do so."
    - "Understand the diverse character types within our team and appreciate that some of us may prefer a description of a meeting in advance to allow  time to prepare."
    - "Keep conversations inclusive to the audience, ensuring that technical detail is fairly high level where possible."
    - "Be mindful of the workload of others even if it does not impact ours directly."
    - "Clarify the importance of attendance in certain meetings, outlining the purpose/objective, and where appropriate an agenda that helps us get to said outcome."
    - "Give informal and continuous feedback especially if the feedback includes encouragement."
    - "We're not ‘working from home’ we are ‘working at home during a crisis’, so we need to take the time that we need during a working day."


govuk-datagovuk:
  members:
    - kentsanggds
    - owenatgov
    - risicle

  channel:
    "#govuk-datagovuk"

  exclude_titles:
    - "[DO NOT MERGE]"
    - "[PROTOTYPE]"
    - WIP
    - "[WIP]"

govuk-frontend-a11y:
  members:
    - danacotoran
    - injms
    - maxgds

  channel:
    "#govuk-frontend-a11y"

  compact: true

  exclude_titles:
    - "[DO NOT MERGE]"
    - "[PROTOTYPE]"
    - WIP
    - "[WIP]"

  quotes:
    - "Be Excellent To Each Other!"
    - ":smiling-batman:"
    - "Don't be working if you're ill!"
    - ":green_heart:"
    - "It's okay to ask for help"
    - "It's okay to depend on the team"
    - "It's okay to take time to learn"
    - "It's okay not know everything"

govuk-notifications:
  members:
    - 1pretz1
    - benthorner
    - kevindew
    - laurentqro

  channel:
    "#govuk-notifications-dev"

  compact: true

  exclude_titles:
    - "[DO NOT MERGE]"
    - "[PROTOTYPE]"
    - WIP
    - "[WIP]"

govuk-platform-health:
  members:
    - AlanGabbianelli
    - beccapearce
    - benjamineskola
    - callumknights
    - cbaines
    - ChrisBAshton
    - deborahchua
    - edwardkerry
    - kentsanggds
    - MuriloDalRi
    - nicholsj
    - Tetrino
    - thomasleese

  channel:
    "#govuk-platform-health"

  exclude_titles:
    - "[DO NOT MERGE]"
    - "WIP"

  quotes:
    - Be ready and willing to pair on work
    - Slack as primary point of contact; email for things you want to remember
    - Assume everyone is trying to do the right thing
    - Look out for each other
    - Make sure every meeting has a purpose and objective and explains who is required
    - Keep stand up updates as short as possible
    - Make sure anyone who wants to be involved in a decision has the opportunity to be
    - Try with each bit of work to upskill others
    - It's okay to spend some time understanding the thing(s) before implementing the solution
    - It's OK to pick up and work on something you don't understand yet

  compact: true

govuk-pay:
  members:
    - heathd
    - alexbishop1
    - cobainc0
    - danworth
    - heathd
    - jonheslop
    - kbottla
    - mrlumbu
    - oswaldquek
    - SandorArpa
    - stephencdaly
    - jankowiakmaria
    - sfount
    - RoryMalcolm

  channel:
    "#govuk-pay-tech"

  exclude_titles:
    - "[DO NOT MERGE]"
    - WIP

govuk-replatforming:
  members:
    - bilbof
    - deanwilson
    - issyl0
    - MahmudH
    - richardTowers
    - seb-szy

  channel:
    "#govuk-replatforming"

  exclude_titles:
    - "[DO NOT MERGE]"
    - WIP
    - "[WIP]"
