# Please insert new items alphabetically.
design-system-dev:
  members:
    - 36degrees
    - christopherthomasdesign
    - hannalaakso
    - joelanman
    - kellylee-gds
    - m-green
    - RosieClayton
    - StephenGill
    - timpaul

  include_repos:
    - accessible-autocomplete
    - design-system-support
    - design-system-team-credentials
    - design-system-team-docs
    - design-system-team-internal
    - design-system-team-labels
    - govuk-design-system
    - govuk-design-system-architecture
    - govuk-design-system-backlog
    - govuk-frontend
    - govuk-frontend-docs
    - govuk-prototype-kit
    - govuk-prototype-kit-docs
    - govuk_elements
    - govuk_elements_rails
    - govuk_frontend_toolkit
    - govuk_frontend_toolkit_gem
    - govuk_frontend_toolkit_npm
    - govuk_template
    - prototype-kit-training

  channel:
    "#design-system-dev"

  exclude_titles:
    - DO NOT MERGE
    - WIP

  compact: true

digitalmarketplace:
  members:
    - lfdebrux
    - gidsg
    - agalamatis
    - katstevens
    - phantas
    - domoscargin

  channel:
    "#dm-review"

  exclude_titles:
    - WIP

  include_repos:
    - "digitalmarketplace-admin-frontend"
    - "digitalmarketplace-agreements"
    - "digitalmarketplace-antivirus-api"
    - "digitalmarketplace-api"
    - "digitalmarketplace-apiclient"
    - "digitalmarketplace-aws"
    - "digitalmarketplace-bad-words"
    - "digitalmarketplace-brief-responses-frontend"
    - "digitalmarketplace-briefs-frontend"
    - "digitalmarketplace-buyer-frontend"
    - "digitalmarketplace-content-loader"
    - "digitalmarketplace-credentials"
    - "digitalmarketplace-design-patterns"
    - "digitalmarketplace-docker-base"
    - "digitalmarketplace-frameworks"
    - "digitalmarketplace-frontend-toolkit"
    - "digitalmarketplace-functional-tests"
    - "digitalmarketplace-govuk-frontend"
    - "digitalmarketplace-jenkins"
    - "digitalmarketplace-logdia"
    - "digitalmarketplace-manual"
    - "digitalmarketplace-performance-testing"
    - "digitalmarketplace-router"
    - "digitalmarketplace-runner"
    - "digitalmarketplace-scripts"
    - "digitalmarketplace-search-api"
    - "digitalmarketplace-supplier-frontend"
    - "digitalmarketplace-test-utils"
    - "digitalmarketplace-user-frontend"
    - "digitalmarketplace-utils"
    - "digitalmarketplace-visual-regression"
    - "govuk-frontend-jinja"

  compact: false

govuk-corona-product:
  members:
    - andysellick
    - DilwoarH
    - hannako
    - sihugh

  channel:
    "#govuk-corona-product"

  compact: true

  exclude_titles:
    - "[PROTOTYPE]"
    - WIP
    - "[WIP]"

govuk-coronavirus-notifications:
  members:
    - benthorner
    - chao-xian
    - laurentqro
    - vanitabarrett

  channel:
    "#govuk-coronavirus-notifications"

  compact: true

  exclude_titles:
    - "[DO NOT MERGE]"
    - "[PROTOTYPE]"
    - WIP
    - "[WIP]"

govuk-data-labs:
  members:
    - bevanloon
    - ff-l
    - karlbaker02
    - mammykins
    - nacnudus
    - oscarwyatt
    - suganya-s
    - trvllngmn
    - VitalieMogoreanu

  channel:
    "#govuk-data-labs"

  exclude_titles:
    - "[DO NOT MERGE]"
    - "[PROTOTYPE]"
    - WIP
    - "[WIP]"

govuk-frontend-a11y:
  members:
    - chao-xian
    - injms
    - maxgds

  channel:
    "#govuk-frontend-a11y"

  compact: true

  exclude_titles:
    - "[DO NOT MERGE]"
    - "[PROTOTYPE]"
    - WIP
    - "[WIP]"

  quotes:
    - "Be Excellent To Each Other!"
    - ":smiling-batman:"
    - "Don't be working if you're ill!"
    - ":green_heart:"
    - "It's okay to ask for help"
    - "It's okay to depend on the team"
    - "It's okay to take time to learn"
    - "It's okay not know everything"

govuk-datagovuk:
  members:
    - kentsanggds
    - maxgds
    - risicle

  channel:
    "#govuk-datagovuk"

  exclude_titles:
    - "[DO NOT MERGE]"
    - "[PROTOTYPE]"
    - WIP
    - "[WIP]"

govuk-platform-health:
  members:
    - 1pretz1
    - AlanGabbianelli
    - barrucadu
    - beccapearce
    - benjamineskola
    - callumknights
    - cbaines
    - ChrisBAshton
    - deborahchua
    - edwardkerry
    - kentsanggds
    - MahmudH
    - MuriloDalRi
    - nicholsj
    - Tetrino
    - thomasleese

  channel:
    "#govuk-platform-health"

  exclude_titles:
    - "[DO NOT MERGE]"
    - "WIP"

  quotes:
    - Be ready and willing to pair on work
    - Slack as primary point of contact; email for things you want to remember
    - Assume everyone is trying to do the right thing
    - Look out for each other
    - Make sure every meeting has a purpose and objective and explains who is required
    - Keep stand up updates as short as possible
    - Make sure anyone who wants to be involved in a decision has the opportunity to be
    - Try with each bit of work to upskill others
    - It's okay to spend some time understanding the thing(s) before implementing the solution
    - It's OK to pick up and work on something you don't understand yet

  compact: true

govuk-pay:
  members:
    - heathd
    - alexbishop1
    - cobainc0
    - danworth
    - heathd
    - jonheslop
    - kbottla
    - mrlumbu
    - oswaldquek
    - SandorArpa
    - stephencdaly
    - jankowiakmaria
    - sfount
    - RoryMalcolm

  channel:
    "#govuk-pay-tech"

  exclude_titles:
    - "[DO NOT MERGE]"
    - WIP

govuk-corona-services:
  members:
    - alex-ju
    - bilbof
    - brucebolt
    - gclssvglx
    - huwd
    - injms
    - issyl0
    - JonathanHallam
    - leenagupte
    - richardTowers
    - Rosa-Fox
    - steveholmes

  channel:
    "#govuk-corona-services-tech"

  exclude_titles:
    - "DO NOT MERGE"
    - "🚧"
    - "[WIP]"
    - "[Do Not Merge]"

  include_repos:
    - govuk-coronavirus-business-volunteer-form
    - govuk-coronavirus-find-support
    - govuk-coronavirus-vulnerable-people-form
    - govuk-developer-docs
